### ISSUE TITLE
ImportError: cannot import name 'images' from 'modules'

### ISSUE THREAD

**Issue by jammyfu** [ssitu/ComfyUI_UltimateSDUpscale#56]
When I update Manager: V2.7, comfyUI version to 1948[4c54c2](2024-02-01), I get this error：
Traceback (most recent call last):
  File "D:\AIGCTool\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AIGCTool\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\__init__.py", line 24, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\AIGCTool\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\nodes.py", line 5, in <module>
    from usdu_patch import usdu
  File "D:\AIGCTool\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\usdu_patch.py", line 2, in <module>
    from repositories import ultimate_upscale as usdu
  File "D:\AIGCTool\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\__init__.py", line 14, in <module>
    spec.loader.exec_module(ultimate_upscale)
  File "D:\AIGCTool\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\ultimate_sd_upscale\scripts\ultimate-upscale.py", line 4, in <module>
    from modules import processing, shared, images, devices, scripts
ImportError: cannot import name 'images' from 'modules' (D:\AIGCTool\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\modules\__init__.py)

**Comment by epicstar7** [comment]
Same issue here

**Comment by zeonagames** [comment]
Same issuue, Please help @ssitu

**Comment by ssitu** [comment]
It seems to be a conflict with the reactor node extension.

**Comment by zeonagames** [comment]
> It seems to be a conflict with the reactor node extension.

I am using Comfyui manager I just install failed

![eraxcad](https://github.com/ssitu/ComfyUI_UltimateSDUpscale/assets/105548211/93b1711b-58c6-4444-8200-bfca43392864)

**Comment by ssitu** [comment]
> > It seems to be a conflict with the reactor node extension.
> 
> 
> 
> I am using Comfyui manager I just install failed
> 
> 
> 
> ![eraxcad](https://github.com/ssitu/ComfyUI_UltimateSDUpscale/assets/105548211/93b1711b-58c6-4444-8200-bfca43392864)
> 
> 

Do you have reactor face swap node installed?

**Comment by zeonagames** [comment]
> > > It seems to be a conflict with the reactor node extension.
> > 
> > 
> > I am using Comfyui manager I just install failed
> > ![eraxcad](https://private-user-images.githubusercontent.com/105548211/303536973-93b1711b-58c6-4444-8200-bfca43392864.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0NDU4NTYsIm5iZiI6MTcwNzQ0NTU1NiwicGF0aCI6Ii8xMDU1NDgyMTEvMzAzNTM2OTczLTkzYjE3MTFiLTU4YzYtNDQ0NC04MjAwLWJmY2E0MzM5Mjg2NC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOVQwMjI1NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOTRiYmQ5MzkxNzNjMGY3NmU0YjE3MDMyMDIyMGY2OTA5NDMxMmEwNzM0NzkyNGJiOWRjNDEzMjE3ZWY4ZjdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UwwcawpH2GlK-M3vpHlvdOPxmukilaqVRx8sxN1biBU)
> 
> Do you have reactor face swap node installed?

I just have those 
![Screenshot 2024-02-09 at 05-27-56 ComfyUI](https://github.com/ssitu/ComfyUI_UltimateSDUpscale/assets/105548211/7d6394b9-13d1-4078-a8b8-f786507b9040)

**Comment by zeonagames** [comment]
` File "F:\Programlar\Pinokio\api\comfyui.git\app\custom_nodes\ComfyUI_UltimateSDUpscale\__init__.py", 
line 24, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "F:\Programlar\Pinokio\api\comfyui.git\app\custom_nodes\ComfyUI_UltimateSDUpscale\nodes.py", lin
e 5, in <module>
    from usdu_patch import usdu
  File "F:\Programlar\Pinokio\api\comfyui.git\app\custom_nodes\ComfyUI_UltimateSDUpscale\usdu_patch.py"
, line 2, in <module>
    from repositories import ultimate_upscale as usdu
  File "F:\Programlar\Pinokio\api\comfyui.git\app\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\_
_init__.py", line 14, in <module>
    spec.loader.exec_module(ultimate_upscale)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\Programlar\\Pinokio\\api\\comfyui.git\\app
\\custom_nodes\\ComfyUI_UltimateSDUpscale\\repositories\\ultimate_sd_upscale\\scripts\\ultimate-upscale
.py'

Cannot import F:\Programlar\Pinokio\api\comfyui.git\app\custom_nodes\ComfyUI_UltimateSDUpscale module f
or custom nodes: [Errno 2] No such file or directory: 'F:\\Programlar\\Pinokio\\api\\comfyui.git\\app\\
custom_nodes\\ComfyUI_UltimateSDUpscale\\repositories\\ultimate_sd_upscale\\scripts\\ultimate-upscale.p
y'`     This code gives error from init.py from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]   @ssitu

**Comment by ssitu** [comment]
I installed the same ones you have and I have no problems loading. I'm not sure what's the problem.

**Comment by zeonagames** [comment]
This code gives error from init.py     

from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]   @ssitu

**Comment by zeonagames** [comment]
I SOLVED, because There is no script file in there  Download this scripts folder from there 
https://github.com/Coyote-A/ultimate-upscale-for-automatic1111/tree/756bb50573ccc86ad2620b49f01f46d91a6fd682

and copy the scripts folder to  custom_nodes\ComfyUI_UltimateSDUpscale\repositories\ultimate_sd_upscale\ 

Reset comfyui thats it

**Comment by BigUncle** [comment]
> I SOLVED, because There is no script file in there  Download this scripts folder from there 
> 
> https://github.com/Coyote-A/ultimate-upscale-for-automatic1111/tree/756bb50573ccc86ad2620b49f01f46d91a6fd682
> 
> 
> 
> and copy the scripts folder to  custom_nodes\ComfyUI_UltimateSDUpscale\repositories\ultimate_sd_upscale\ 
> 
> 
> 
> Reset comfyui thats it
> 
> 
> 
> 
Yes.
I update the submodule and it works.

https://github.com/ssitu/ComfyUI_UltimateSDUpscale/issues/62#issuecomment-1984923872
